name: CI Hexlet course

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build app
        run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: npm test
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run linter
        run: npm run lint
