name: CI Hexlet course
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: make setup
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: make test
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run linter
        run: make lint
